edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"

imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

fn_single_line = false
where_single_line = false
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true

struct_lit_single_line = true
enum_discrim_align_threshold = 20

wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true

match_block_trailing_comma = true
match_arm_leading_pipes = "Never"
match_arm_blocks = true

format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = false

blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
condense_wildcard_suffixes = false
force_explicit_abi = true
force_multiline_blocks = false
hex_literal_case = "Upper"
